### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by zaaack** [andreypopp/ppx_let_promise#1]
Hi, I'm new to ReasonML/OCaml, just follow the readme, but I got an error: Error: Uninterpreted extension 'bind'. BTW, my bsc version is 
BuckleScript 1.8.1 (Using OCaml4.02.3+BS )

**Comment by andreypopp** [comment]
What's your `bsconfig.json`? It should include `ppx_let` config as shown in the README.

**Comment by zaaack** [comment]
@andreypopp I just tried on my Linux laptop and worked! (With `open Ppx_let_promise;;` in the top of file, which could be helpful for new bees like me if readme can mention it) The error was thrown in my MacBook (which currently not in my around, I'll try it tomorrow). By the way, can this support ReasonML?

**Comment by andreypopp** [comment]
Reasonml doesn't have nice syntax for ppx at the moment. While it is
possible to do so (reasonml -> ocaml + ppx -> ocaml) it won't be as nice as
using ocaml, I believe.

**Comment by zaaack** [comment]
@andreypopp Test on MacBook and it works! I didn't return a promise and misunderstood the error message. This error(Error: Uninterpreted extension 'bind') must be thrown in the ReasonML files.

Just create a PR to add full demo in README to help more newbies like me: https://github.com/andreypopp/ppx_let_promise/pull/2
